### ISSUE TITLE
Dependence missing

### ISSUE THREAD

**Issue by tgamauf** [adrianhall/masterdetailtemplate#1]
Hi,

the dependency "react-native-swipeout": "adrianhall/react-native-swipeout#types" is missing - you don't have a public repo of this name.

Would be nice if you could add it!

Thanks,
Thomas

**Comment by adrianhall** [comment]
You can just include react-native-swipeout now as my change got merged.  I'll update the template.

**Comment by adrianhall** [comment]
Fixed!
